services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spirox-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - spirox-network

  nginx:
    image: nginx:alpine
    container_name: spirox-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/:ro
    networks:
      - spirox-network

networks:
  spirox-network:
    driver: bridge
